const colors = {
    dark_theme: {
      backgroundColor: '#000',
      primaryColor: '#E4002B',
      green: '#35AA4E',
      normalTextColor: '#fff',
      white: '#fff',
      black: '#000',
      lineColor: '#DADADA',
      textColor: '#373737',
      dividerColor: '#DFE0E3',
      catBackgroundColor: '#F8F9FF',
      dotColor: '#ACACAC',
      barColor: '#D9D9D9',
      light_blue: '#EEF1FC',
      light_red: '#FFD2D2',
      light: '#FFECEF',
      placeholder_color: '#D7D7D7',
      borderColor: '#E9EBF4',
      titleColor: '#3D3B40',
      subtitleColor: '#818181',
      username: '#8C8C8C',
      success: '#28B446',
    },
    light_theme: {
      backgroundColor: '#fff',
      primaryColor: '#E4002B',
      green: '#35AA4E',
      normalTextColor: '#000',
      white: '#fff',
      black: '#000',
      lineColor: '#DADADA',
      textColor: '#373737',
      dividerColor: '#DFE0E3',
      catBackgroundColor: '#F8F9FF',
      dotColor: '#ACACAC',
      barColor: '#D9D9D9',
      light_blue: '#EEF1FC',
      light_red: '#FFD2D2',
      light: '#FFECEF',
      placeholder_color: '#D7D7D7',
      borderColor: '#E9EBF4',
      titleColor: '#3D3B40',
      subtitleColor: '#818181',
      username: '#8C8C8C',
      success: '#28B446',
    },
  };
  
  export default colors;
  